[package]
name = "csctrl"
version = "0.1.0"
edition = "2021"
authors = ["joaofonseca.dev"]
description = "Manager for Counter-Strike 2 servers"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
